name: "go-checkout-script"
description: "quick and dirty git checkout for public repos that run on linux workflows"
inputs:
  token:
    description: "authentication token for private repositories"
    required: false
  repo:
    description: "repository to clone"
    required: false
runs:
  using: composite
  steps:
    - name: "run linux binary"
      if: runner.os == 'linux'
      run: ${{ github.action_path }}/builds/linux-amd64-build
      shell: bash
      env:
        GH_REPO_LINK: ${{ inputs.repo }} 
        GH_REPO_ACCESS_TOKEN: ${{ inputs.token }}
        GH_DEFAULT_REPO: ${{ github.event.repository.url }}
        GH_WORKSPACE: ${{ github.workspace }}

    - name: "run windows binary"
      if: runner.os == 'windows'
      run: ${{ github.action_path }}/builds/windows-amd64-build
      shell: bash
      env:
        GH_REPO_LINK: ${{ inputs.repo }} 
        GH_REPO_ACCESS_TOKEN: ${{ inputs.token }}
        GH_DEFAULT_REPO: ${{ github.event.repository.url }}
        GH_WORKSPACE: ${{ github.workspace }}
