name: "go-checkout-script"
description: "quick and dirty git checkout on linux workflows written in go"
inputs:
  repo:
    description: "repository to clone"
    required: false
runs:
  using: composite
  steps:
    - name: "run go binary"
      run: ${{ github.action_path }}/builds/linux-amd64-build #running off build, move this to detect env possibly
      shell: bash
      env:
        GH_REPO_LINK: ${{ inputs.repo }} 
        GH_DEFAULT_REPO: ${{ github.event.repository.url }}
        GH_WORKSPACE: ${{ github.workspace }}
