name: "tests"
run-name: "tests"
on:
  push:
    branches: fix/pipeline
    paths: 
      - main.go
      - action.yaml
      - builds/*

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: clone repository code
        uses: jake-young-dev/go-checkout-script@fix/pipeline

      - name: check for build file
        shell: bash
        run: test -f ./builds/linux-amd64-build