name: "tests"
run-name: "tests"
on:
  push:
    branches: fix/pipeline
    paths: 
      - main.go
      - action.yaml
      - builds/*

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: clone repo
        uses: jake-young-dev/go-checkout-script@master

      - name: check for files
        shell: bash
        run: ls -l

      - name: check for files
        shell: bash
        run: ls /builds