name: "tests"
run-name: "tests"
on:
  push:
    branches: master
    paths: 
      - main.go
      - action.yaml
      - builds/*

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: clone repo
        uses: jake-young-dev/go-checkout-script@master

      - name: check for build files
        shell: bash
        run: test -f /builds/linux-amd64-build