name: "tests"
run-name: "tests"
on:
  push:
    branches: master
    paths: 
      - main.go
      - action.yaml
      - builds/*

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: check for files
        shell: bash
        run: ls 

      - name: test pull
        uses: jake-young-dev/go-checkout-script@master
        with:
          repo: https://github.com/jake-young-dev/go-install-script

      - name: check for files
        shell: bash
        run: ls -la
      
      - name: check for files
        shell: bash
        run: ls builds/